version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_DB=discountdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  orderdb:
    container_name: orderdb
    restart: always
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  consul:
    container_name: consul
    restart: always
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    ports:
      - "8500:8500"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=4001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "IdentityServer:BaseUrl=https://consul"
      - "ServiceConfig:serviceDiscoveryAddress=https://identityserver"
      - "ServiceConfig:serviceAddress=https://catalog.api"
    depends_on:
      - catalogdb
      - identityserver
      - consul
    ports:
      - "4001:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=4002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=https://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "IdentityServer:BaseUrl=https://identityserver"
      - "ServiceConfig:serviceDiscoveryAddress=https://identityserver"
      - "ServiceConfig:serviceAddress=https://basket.api"
    depends_on:
      - basketdb
      - rabbitmq
      - identityserver
      - consul
    ports:
      - "4002:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=4003
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=discountdb;User Id=admin;Password=admin12345;"
      - "ServiceConfig:serviceDiscoveryAddress=https://identityserver"
      - "ServiceConfig:serviceAddress=https://discount.api"
    depends_on:
      - discountdb
      - consul
    ports:
      - "4003:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=4004
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=discountdb;User Id=admin;Password=admin12345;"
    depends_on:
      - discountdb
    ports:
      - "4004:443"
    volumes:
      - ~/.aspnet/https:/https:ro


  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=4005
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "IdentityServer:BaseUrl=https://identityserver"
      - "ServiceConfig:serviceDiscoveryAddress=https://identityserver"
      - "ServiceConfig:serviceAddress=https://ordering.api"
    depends_on:
      - orderdb
      - rabbitmq
      - identityserver
      - consul
    ports:
      - "4005:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=4000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "IdentityServer:BaseUrl=https://identityserver"
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
      - identityserver
      - consul
    ports:
      - "4000:443"
    volumes:
      - ~/.aspnet/https:/https:ro


  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=4006
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ApiSettings:CatalogUrl=https://catalog.api"
      - "ApiSettings:BasketUrl=https://basket.api"
      - "ApiSettings:OrderingUrl=https://ordering.api"
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "4006:443"
    volumes:
      - ~/.aspnet/https:/https:ro


  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ApiSettings:GatewayAddress=https://ocelotapigw"
      - "IdentityServer:BaseUrl=https://identityserver"
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
      - identityserver
    ports:
      - "5000:443"
    volumes:
      - ~/.aspnet/https:/https:ro


  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=5050
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "WebClientBaseAddress=https://aspnetrunbasics"
    ports:
      - "5050:443"
    volumes:
      - ~/.aspnet/https:/https:ro
